<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PitchReserve.Application\PitchReserve.Application.csproj" />
    <ProjectReference Include="..\PitchReserve.Domain\PitchReserve.Domain.csproj" />
  </ItemGroup>

</Project>
